FROM eclipse-temurin:21

LABEL maintainer="namdeoswaraj@gmail.com"

WORKDIR /app

COPY target/Employee-Management-Backend-0.0.1-SNAPSHOT.jar /app/Employee-Management-Backend-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "Employee-Management-Backend-0.0.1-SNAPSHOT.jar"]